name: E2E Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'

      - name: Install Go dependencies
        run: go get -t -v ./...

      - name: Run dependencies
        run: bash ./tools/setup.sh

      - name: Run test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
