name: E2E Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Install Go dependencies
        run: |
          go get -t -v ./...
          go get github.com/onsi/ginkgo/ginkgo
          sudo cp ~/go/bin/ginkgo /usr/local/bin

      - name: Setup test environment
        run: bash ./tools/setup.sh

      - name: Run test
        run: make test

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)

      # Debug via SSH if previous steps failed
      - name: Set up tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v2
        with:
          timeout-minutes: 15
